name: Docker

on:
  push:
    branches:
      - master

    tags:
      - v*

  pull_request:

env:
  IMAGE_NAME: buffalo

jobs:
  push:
    runs-on: ubuntu-latest
    if: github.event_name == 'push'

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Build image
        run: docker build . --tag $IMAGE_NAME

      - name: Push to Docker Hub
        uses: docker/build-push-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          repository: marekhanzal/buffalo
          tag_with_ref: true
